language: node_js
node_js:
  - "node"
script: npm run build -- --prod
before_deploy: "cd functions && npm install && cd .."
deploy:
  provider: firebase
  on: master
  skip_cleanup: true
  token:
    secure: "E1kdSI17VyYQEC+9WqSTeDVV8Xy6e4rpHqsKU9gZV1oNyrhF9gZIkh2UQSYTSnSnxraMg7FgF4fbC597Rcl3vzmaVmhx/tjgGdlhkeHMynrhiTseL1Zj4yG7lc/Tf1cM8QhQfDEoAyApUMe4RobsywI0cZ9I9ZwQHEIqmBYJGBtS+W4lUOLZfXtXerXHCLe+nB+m10XA9rhIjLWocL5p39tUQu+4/hV/IMTR0T+45Eefugpr2fKyOxxHG1XEpduSE6wPrj9DTU3ARTXV1GDK04CEX2gmLOwxVFCMIvBRpmk/pQ5Udz+J/DVytj9Mj/kBoeWMB3Ezd73cYjd3qhHjjdbmTWcSdT46QzuyWdbGgVGLjZDnah94Wv1KGdn+tux6lw1RHgAbLI0FgUH9+0/6sE6sLuIGeLDGUmugm65Re88H5VXSRkgzKVPSJ21xoEmXPImX2RifoQT1ISLjJPZ13mbUtyalwWfWucAhScqxl+OW63r2a6xTaPZFDuK7CXQC/5PhTDKUV1qQ9BPYb78UVc9z8CZ133ml52Ltf0MitORpQMw/kjzolaGLaVQkUOmutGKnBYdNUFRA+TonmMA63gOdTEiWHwawLockHvcII3VocpvQU2FnjxCJq9WRUIDpCvdBMJQuBAsY5bd3Ndv3m5dWOScl3VOFiHJQ6tktyGI="
